# Generated by Django 5.2 on 2025-04-07 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_reservation_options_alter_room_options_and_more'),
    ]

    operations = [
    ]
