# Generated by Django 5.2 on 2025-04-30 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_room_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Payé'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut du paiement')),
                ('payment_date', models.DateTimeField(auto_now_add=True, verbose_name='Date du paiement')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Méthode de paiement')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='ID de transaction')),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='rooms.reservation', verbose_name='Réservation')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
            },
        ),
    ]
